name: obsidian_flm_desktop
description: Local-first desktop client for Obsidian_FLM.
publish_to: none
version: 0.1.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  webview_windows: any
  dio: any
  html: any
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
